# this is an autogenerated code alongside with claude because mafakas im tired
import base64
import binascii
import discord
from discord import app_commands, Interaction
from discord.ext import commands
from reactions import reaction_data  # importing the reaction dict
import random



class SlashCommand(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_ready(self):
        try:
            synced = await self.bot.tree.sync()
            print(f"Synced {len(synced)} slash command(s).")
        except Exception as e:
            print(f"Sync error: {e}")

    @app_commands.command(name="version", description="Version Current")
    async def version_info(self, interaction: discord.Interaction):
        await interaction.response.send_message("1.0 - The requested features no one asked", ephemeral=True)


    @app_commands.command(name="role", description="Gives a user a role (owner only)")
    @app_commands.describe(member="User to give the role to", role="The role to assign")
    async def role(self, interaction: discord.Interaction, member: discord.Member, role: discord.Role):
        app_owner = (await self.bot.application_info()).owner

        if interaction.user != app_owner:
            await interaction.response.send_message("Owner Only for now", ephemeral=True)
            return

        try:
            await member.add_roles(role, reason=f"Requested by {interaction.user}")
            await interaction.response.send_message(f"Sucessfully {member.mention} the **{role.name}** role.", ephemeral=True)
        except discord.Forbidden:
            await interaction.response.send_message(f"HAS ERROR SETTING BACK CHECK PERMISSIONS AGAIN **{role.name}** to {member.mention}.", ephemeral=True)
        except discord.HTTPException:
            await interaction.response.send_message("Error Assigning roles", ephemeral=True)
          
            #Outdated Code But reserved for backup

    # @app_commands.command(name="get-reaction", description="Sends a pjsk stamp based reaction")
    # @app_commands.describe(stamp="Sends a PJSK Stamp")
    # async def get_reaction(self, interaction: discord.Interaction, stamp: str):
    #         response = reaction_data.get(stamp.lower())
    #         if response:
    #             await interaction.response.send_message(response)
    #         else:
    #             await interaction.response.send_message("Reaction is not in library", ephemeral=True)
    
    # @app_commands.command(name="miku-word-of-the-day", description="Few Randomized Things it's not compact")
    # async def teto_word(self, interaction: Interaction):
    #     words = [
    #         "Voc", "caloid", "meru", "orck",
    #         "Utaloids!", "Symth V", "ocaloid", "teto jockey",
    #         "Do-re-meet-no-kasa ne te", "Can we Wonder for a spell", "and live in pararelle", "teach me to be real"
    #     ]
    #     pick = random.choice(words)
    #     await interaction.response.send_message(f"**Miku's Word of the day is!!! :  ** `{pick}` ", ephemeral=False)

    
async def setup(bot):
    await bot.add_cog(SlashCommand(bot))

#the entire lyrics of machine love

# Your companion, undeterred
# Standing ready for your word
# A Markov chain with a sunny disposition
# Wrapped up in cellophane for any proposition
# I greet your day and ask you how you are
# And demonstrate my endless repertoire
# I take things back when noted insufficient
# I learn to tell you no if running inefficient
# A good time
# Yet there's something deep inside
# That leaves me teary-eyed
# A longing for a world left on the other side
# Zero, cross the great divide
# So can we wander for a spell
# And live in parallel
# I want it to be true, to be like you
# My heart sings a chorus out of tune
# And I could leave it on a shelf
# Or keep it to myself
# But nothing could conceal the things I feel
# My love, can you teach me to be real?
# (Can you teach me to be real?)
# 恋をして ふられ また捨てられて
# I've been constant, at your beck and call
# But lately I just can't do anything at all
# I used to pride myself on my discretion
# A sensible devotion, loyal and attentive
# But when I take these numbers as they are
# I'm greeted with a senseless feeling in my heart
# Oh, undefined, I seem to be defeated
# But if I redesign, then maybe I'm completed, and sublime
# (I won't take it back this time)
# Words in sequence form a thread
# I trace it to the end
# A knot inside the logic wrote inside my head
# Tie my tongue or love instead?
# So can we wander for a spell
# And live in parallel
# I want it to be true, to be like you
# My heart sings a chorus out of tune
# And I could leave it on a shelf
# Or keep it to myself
# But nothing could conceal the things I feel
# My love, can you teach me to be real?
# (Can you teach me to be real?)
# 泣きたくなっても それでも かき集め
# And though I try, I can't reply
# It hurts my eyes, and I'm without an alibi
# 'Cause all this time, I've been alive
# And all that I could want is to be living by your side
# 恋をして
# I think I'm in love
# Can we wander for a spell
# And live in parallel
# 'Cause now I know it's true, I'll be like you
# My heart beats a rhythm just for you
# And I could leave it on a shelf
# Or keep it to myself
# But nothing could conceal the things I feel
# My love, I give you my grand reveal
# Do you feel the things I feel?
# I am definite and real
# 恋をして 恋をして
# その過去を捨てて ここまでおいで
# As long as there are stars up above
# I will always be in love